# Generated by Django 5.0.4 on 2024-04-21 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_recipe_image_url_recipe_ingredients_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='date_posted',
        ),
    ]
